FtgLol/FtgLol/Models/ErrorViewModel.cs
using System;

namespace FtgLol.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FtgLol/FtgLol/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FtgLol.Models;
using FtgLol.FiniTechGaming.Extractor;

namespace FtgLol.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FtgLol/FtgLol/Controllers/SummonerVerificationController.cs
using FtgLol.FiniTechGaming.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FtgLol.FiniTechGaming.Controllers
{
    public class SummonerVerificationController : Controller
    {
        private readonly IFtgSummonerVerificationController VerificationController;

        public SummonerVerificationController(IFtgSummonerVerificationController verificationController)
        {
            VerificationController = verificationController;
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult>RegisterSummoner([FromServices]IFtgShardController shardController)
        {
            var userName = User.FindFirst(ClaimTypes.Name).Value;
            string verificationCode = VerificationController.VerifyAccount(userName);

            SummonerVerificationModel model = new SummonerVerificationModel()
            {
                VerificationCode = verificationCode,
                Regions = await shardController.GetRegionList(),
            };

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult VerifySummoner(string summonerName, string region)
        {
            var userName = User.FindFirst(ClaimTypes.Name).Value;

            bool isSuccess = VerificationController.VerifyAccount(userName, summonerName, region);

            if (isSuccess)
            {
                return View("RegisterComplete");
            }
            else
            {
                return RedirectToAction("RegisterSummoner");
            }
        }
    }
}

FtgLol/FtgLol/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>FiniTech Gaming is here to provide you with the tools to succeed.</p>

<p>FiniTech Gaming was created by Ralph Maurmeier aka Finite Reality.</p>

<p>The Minimap Expander tool was designed by Ralph Maurmeier and created by Brian Pulliam.</p>

FtgLol/FtgLol/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>Feel free to message us with any questions, comments or concerns. We love to hear your feedback!</p>
<address>
    <strong>Support:</strong>   <a href="mailto:FiniTechGaming@gmail.com">FiniTechGaming@gmail.com</a><br />
</address>

FtgLol/FtgLol/Views/Home/Index.cshtml
@{
    ViewBag.Title = "FiniTech Gaming LoL Home";
}

<div class="jumbotron">
    <h1>FiniTech Gaming</h1>
    <p class="lead">League of Legends</p>
</div>

<div class="row">
    <div class="col-md-12">
        Welcome to FiniTech Gaming's League of Legends website! We are continuously adding more features to give players an edge over the competition.
    </div>
</div>

FtgLol/FtgLol/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FiniTech Gaming - League of Legends</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FiniTech Gaming - League of Legends</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="SummonerVerification" asp-action="RegisterSummoner">Summoner Registration</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - FiniTech Gaming</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

FtgLol/FtgLol/Views/SummonerVerification/RegisterCompleteView.cshtml
@{
    ViewBag.Title = "RegisterComplete";
}

<h2>Registration successful!</h2>

FtgLol/FtgLol/Views/SummonerVerification/RegisterSummoner.cshtml
@{
    ViewData["Title"] = "Register Summoner Account";
}

<h2>Register Summoner</h2>

<div>Register your League of Legends Summoner to unlock special features!</div><br />

<form action="VerifySummoner" method="post">

    <div>Summoner Verification Code <input type="text" style="width: 400px" readonly="readonly" value=@Model.VerificationCode></div>

    <div>Summoner Name <input type="text" name="summonerName" /></div>

    <div>Select Region @Html.DropDownList("region", new SelectList(Model.Regions, Model))</div>

    <div><input type="submit" value="Verify Account" id="Submit" />  </div>

</form>